---
- name: restart mysql
  service:
    name: mariadb
    state: restarted

- name: restart apache
  service:
    name: httpd
    state: restarted

- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted
